CREATE TABLE IF NOT EXISTS public.train_ds_clean
(
    label integer,
    period character varying COLLATE pg_catalog."default",
    subject_type character varying COLLATE pg_catalog."default",
    subject_name character varying COLLATE pg_catalog."default",
    city_name character varying COLLATE pg_catalog."default",
    hex character varying COLLATE pg_catalog."default",
    hex_lat numeric,
    hex_lon numeric,
    f1 numeric,
    f2 numeric,
    f3 numeric,
    f4 numeric,
    f5 numeric,
    f6 numeric,
    f7 numeric,
    f8 numeric,
    f9 numeric,
    f10 numeric,
    f11 numeric,
    f12 numeric,
    f13 numeric,
    f14 numeric,
    f15 numeric,
    f16 numeric,
    f17 numeric,
    f18 numeric,
    f19 numeric,
    f20 numeric,
    f21 numeric,
    f22 numeric,
    f23 numeric,
    f24 numeric,
    f25 numeric,
    f26 numeric,
    f27 numeric,
    f28 numeric,
    f29 numeric,
    f30 numeric
)



CREATE TABLE IF NOT EXISTS public.test_ds_final
(
    label integer,
    period character varying COLLATE pg_catalog."default",
    subject_type character varying COLLATE pg_catalog."default",
    subject_name character varying COLLATE pg_catalog."default",
    city_name character varying COLLATE pg_catalog."default",
    hex character varying COLLATE pg_catalog."default",
    hex_lat numeric,
    hex_lon numeric,
    f1 numeric,
    f2 numeric,
    f3 numeric,
    f4 numeric,
    f5 numeric,
    f6 numeric,
    f7 numeric,
    f8 numeric,
    f9 numeric,
    f10 numeric,
    f11 numeric,
    f12 numeric,
    f13 numeric,
    f14 numeric,
    f15 numeric,
    f16 numeric,
    f17 numeric,
    f18 numeric,
    f19 numeric,
    f20 numeric,
    f21 numeric,
    f22 numeric,
    f23 numeric,
    f24 numeric,
    f25 numeric,
    f26 numeric,
    f27 numeric,
    f28 numeric,
    f29 numeric,
    f30 numeric,
    id integer
)
